<?php

namespace frontend\models\work\order;

use common\components\dictionaries\base\NomenclatureDictionary;
use common\components\traits\ErrorTrait;
use common\helpers\ErrorAssociationHelper;
use DomainException;
use frontend\services\order\OrderMainService;
use common\events\EventTrait;
use common\helpers\DateFormatter;
use common\repositories\order\OrderMainRepository;
use Yii;
use function PHPUnit\Framework\throwException;

class OrderMainWork extends DocumentOrderWork
{
    use EventTrait, ErrorTrait;

    public $responsible_id;
    public $names;
    public $orders;
    public $status;
    public $regulations;
    public $archive;
    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'fullNumber' => '№ п/п',
            'orderDate' => 'Дата приказа<br>',
            'orderName' => 'Название приказа',
            'bringName' => 'Проект вносит',
            'executorName' => 'Исполнитель',
            'state' => 'Статус',
            'archive' => 'Архивный приказ',
        ]);
    }
    public function rules()
    {
        return array_merge(parent::rules(), [
            [['scanFile'], 'file', 'skipOnEmpty' => true,
                'extensions' => 'png, jpg, pdf, zip, rar, 7z, tag, txt'],
            [['docFiles'], 'file', 'skipOnEmpty' => true, 'maxFiles' => 10,
                'extensions' => 'xls, xlsx, doc, docx, zip, rar, 7z, tag, txt'],
            [['appFiles'], 'file', 'skipOnEmpty' => true,  'maxFiles' => 10,
                'extensions' => 'ppt, pptx, xls, xlsx, pdf, png, jpg, doc, docx, zip, rar, 7z, tag, txt'],
        ]);
    }

    public function getFullName()
    {
        return parent::getFullName(); // TODO: Change the autogenerated stub
    }

    public function generateOrderNumber()
    {
        $formNumber = $this->order_number;
        $model_date = DateFormatter::format($this->order_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        $year = substr(DateFormatter::format($model_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash), 0, 4);
        $array_number = [];
        $index = 1;
        $upItem = NULL;
        $equalItem = [];
        $downItem = NULL;
        $isPostfix = NULL;
        $records = Yii::createObject(OrderMainRepository::class)->getEqualPrefix($formNumber);
        $array_number = Yii::createObject(OrderMainService::class)->createArrayNumber($records, $array_number);
        $numberPostfix = Yii::createObject(OrderMainService::class)
            ->createOrderNumber($array_number, $downItem, $equalItem, $upItem, $isPostfix, $index, $formNumber, $model_date);
        $this->order_number = $numberPostfix['number'];
        $this->order_postfix = $numberPostfix['postfix'];
    }

    public function beforeValidate()
    {
        $post = Yii::$app->request->post();
        $this->order_copy_id = 1;
        $this->type = DocumentOrderWork::ORDER_MAIN;
        if ($post['OrderMainWork']['archive'] == '0') {
            $this->order_number = NomenclatureDictionary::ADMIN_ORDER;
            $this->generateOrderNumber();
        }
        $this->order_date = DateFormatter::format($this->order_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        return parent::beforeValidate();
    }
}