<?php

namespace frontend\models\work\event;

use frontend\models\work\team\ActParticipantWork;
use common\models\scaffold\ParticipantAchievement;

/** @property ActParticipantWork $actParticipantWork */
class ParticipantAchievementWork extends ParticipantAchievement
{
    const TYPE_PRIZE = 0;
    const TYPE_WINNER = 1;

    public static function fill(
        $actParticipantId,
        $achievement,
        $type,
        $certNumber,
        $nomination,
        $date
    )
    {
        $entity = new static();
        $entity->act_participant_id = $actParticipantId;
        $entity->achievement = $achievement;
        $entity->type = $type;
        $entity->cert_number = $certNumber;
        $entity->nomination = $nomination;
        $entity->date = $date;

        return $entity;
    }

    public function rules()
    {
        return [
            [['act_participant_id', 'type'], 'integer'],
            [['achievement', 'cert_number', 'nomination'], 'string'],
            [['date'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }

    public function getPrettyType()
    {
        switch ($this->type) {
            case self::TYPE_PRIZE:
                return 'Призер';
            case self::TYPE_WINNER:
                return 'Победитель';
            default:
                return '---';
        }
    }

    public function getActParticipantWork()
    {
        return $this->hasOne(ActParticipantWork::class, ['id' => 'act_participant_id']);
    }
}